[package]
name = "ru_torch"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.1"
polars = { version = "0.52", features = ["ndarray", "csv"] }
rand = "0.8"
csv = "1.3"
thiserror = "1.0"
rand_distr = "0.4"
ndarray-rand = "0.4"
